### PR TITLE
new contribution - FM with amplitude envelope in Max/gen~

### PR DESCRIPTION
**Pull request by HighHarmonics2**
Adds new Max example. (Uses an existing ChucK program.) 
Updates README.

The example demonstrates the flexibility of ChucK-Max by showing the combination of synthesis in ChucK with simple DSP processing in Max/gen~.

### CODE REVIEW

**Comment by shakfu** [comment]
@HighHarmonics2 

Thanks for your patch!

**Comment by shakfu** [comment]
@HighHarmonics2 

It's very very cool and polished.. enjoying how you also used gen~ as well...

**Comment by HighHarmonics2** [comment]
Thanks! The amplitude modulation in gen~ was based on something I've used before, so it didn't take too much to add. Adding a one channel delay can add a surprising amount of depth to the sound.

**Comment by shakfu** [comment]
@HighHarmonics2 

Can you please have a look at the project README, I've updated it with a bunch of details about recent changes. Let me know what you think. Thx

**Pull request merged**
