### PR TITLE
FM synthesis example w maxpat and ck

### PR DESCRIPTION
**Pull request by HighHarmonics2**
Adds a new example for FM synthesis.

- examples/max/fmEnvelope.dk
- patchers/fmEnvelope.maxpat

Please review.

### CODE REVIEW

**Comment by shakfu** [comment]
@HighHarmonics2 thanks for this excellent example which sounds great.

I have a few comments;

1.  There was a `chuck~: patchcord outlet out of range: deleting patchcord` error on opening it, although it still worked with this error. (I may have inadvertently introduced this error myself, so please check on your side as well).

2. The font text is smaller than the default so it makes it somewhat difficult to read for those of us with imperfect vision.

3. Since these are supposed to be illustrative of use, it's ok to err on the side of making the patches explicit and and so if the patch is not so compact and shows how the objects are connected, that fine.

Clearly (1) is more important than (2) and (3) which are stylistic comments. If you'd rather not adjust your style, then that fine and we can include this in a `contrib` folder.

**Comment by shakfu** [comment]
@HighHarmonics2 

Ok I fixed (1) which was due to the `2` arg being missing from the object declaration

I renamed the patch to `fmenv` (I hope you don't mind), and placed it in the `patchers/examples` folder. If there's any changes or improvements it'll just go into there.

It's committed so your example is not accepted. Thanks very much!

**Comment by HighHarmonics2** [comment]
Thanks and I appreciate the feedback. I have no problem changing patching style, etc or making changes to follow any standards you want to use (naming conventions, etc). 

I can see my files in the dev branch. Did you want me to make the font changes and remove the hidden objects/patch cords and make another PR?

**Comment by shakfu** [comment]
@HighHarmonics2 
> Thanks and I appreciate the feedback. I have no problem changing patching style, etc or making changes to follow any standards you want to use (naming conventions, etc).

I don't have any stylistic feedback beyond what was already given, but if you press me: lowercase filenames, emphasis on readability and understandability of the patch, use of abstractions / subpatches should be consistent with this.

> I can see my files in the dev branch. Did you want me to make the font changes and remove the hidden objects/patch cords and make another PR?

Sure, but take your time, I usually push changes to the `dev` branch first and then merge into `main` after some testing.

**Pull request closed without merging**
