### PR TITLE
ChucK-max example

### PR DESCRIPTION
**Pull request by HighHarmonics2**
New maxpat example using the ChucK plu3.ck example file.

### CODE REVIEW

**Comment by shakfu** [comment]
Hi @HighHarmonics2 

Thanks for this new example. With the new feature of looking for chuck files inside the directory of the .maxpat which calls them, it makes sense to move these patch-specific files into named subfolders. We can do this one of two ways either 

1. Create a `highharmonics2` folder inside `chuck-max/patchers/contrib` and then move all of the related chucks files there and .maxpat pathchers and where you can write the README.md as you like in that folder.
2. Create a patch-specific folder in `contrib` for each patch with its own .maxpt file, .ck files, README.md, etc..

What's your preference? of course if you choose (1) you could also further organize as you like...

**Comment by shakfu** [comment]
@HighHarmonics2 

First of all this  patch is awesome.. Really like the sequencer + chuck combo.. I think it would be cool if one could vary the chuck patch via arguments (which I'm working on btw) or global variable or some kind of randomness, add shreds, and build up the complexity of the sequence.

While I was testing the idea about putting your patches and chuck files in one folder in `contrib`, I noticed that there was a bug in my file search also which prevented it from finding a local patcher-adjacent chuck file that was included as an argument to `chuck~ 2 <filename.ck>`.

Anyway, I fixed this bug, and tested it again, it works now, and then made, what seemed to me, a natural change so that you have your own `highharmonics2` folder in the `contrib` folder. 

I think this works well, since you can make any changes to that folder and add as many chuck and max patches as you like without potentially affecting other patches which depend on files in the `examples` folder.

Hope this is ok, let me know what you think..

**Comment by HighHarmonics2** [comment]
Thanks for the feedback! I think the sequencer object adds a lot of possibility for easily creating musical patterns, and more so if you have familiarity with the `live.step` object. fyi - I actually don't work with it much. I had wanted to add multiple sequences, which it supports, but I couldn't figure out how to get it to play them individually. It's a robust object with lots of attributes and messages, so after I figure it out more, I may revise the patch. 

I like your ideas of having the the sequence object be able to do more with ChucK other than send it a note number. 

I'm glad you found the bug about the file search. I noticed it also, but didn't get around to raising it. 

Regarding folder options - I actually like option 2 with patch specific folders. Hopefully others will make contributions and I like having them together - as you browse the folders, it puts more focus on the solutions, vs the contributor(s). But either way is fine w me.

**Comment by shakfu** [comment]
@HighHarmonics2 

Thanks for your response on this.

> Regarding folder options - I actually like option 2 with patch specific folders. Hopefully others will make contributions and I like having them together - as you browse the folders, it puts more focus on the solutions, vs the contributor(s). But either way is fine w me.

I'm going to go with option (1) for now, we can always move to (2) later...

Also one more point which will become evident in the next commit: I'm dropping the `info` message and merging it with the `status` msg. That way you, there's just one self-evident way to figure out what's going on...

Also check out the `test_eval.maxpat` demo, I've now added a feature so one can write code in a Max message or textedit widget and spork it...

**Pull request merged**
